version: "3.8"

services:
  flask-app:
    build: .
    volumes:
      - .:/code
    ports:
      - "8080:8080"
    depends_on:
      - redis

  redis:
    image: redis
    ports:
      - "6379:6379"
